# Generated by Django 3.0.8 on 2020-11-03 23:54

import app.core.models.save_reversion_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsProcessed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('items', models.TextField(help_text='List with multiple levels', max_length=100, verbose_name='Input')),
                ('result', models.TextField(help_text='Flatten list output', max_length=100, verbose_name='Output')),
            ],
            options={
                'verbose_name': 'Lista de Items',
                'verbose_name_plural': 'Listas de items',
            },
            bases=(app.core.models.save_reversion_mixin.SaveReversionMixin, models.Model),
        ),
    ]
